PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX cco: <https://www.commoncoreontologies.org/> 
PREFIX obo: <http://purl.obolibrary.org/obo/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

SELECT ?document ?document_field
WHERE {
  ?document obo:BFO_0000178 ?document_field . #has continuant part
  ?document a cco:ont00001298 . #document 
  ?document_field a cco:ont00001243 . #document field
}
