# Title: 
#    No Extra Definition Whitespace
# Constraint Description: 
#    No cco:definition value may have leading or trailing whitespace.    
# Severity:
#    Error 

PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>

SELECT DISTINCT ?element ?value 
WHERE {
  ?element cco:definition ?value .
  FILTER (!isBlank(?element) && (REGEX(str(?value), "^[\\s\r\n]+") || REGEX(str(?value), "[\\s\r\n]+$")))
  BIND (concat("ERROR: The following cco:definition values have leading or trailing whitespace ", str(?element)) AS ?error)
}
ORDER BY ?element