# Title: 
#    No Duplicate Definitions
# Constraint Description: 
#    No two ontology elements may have the exact same definition.    
# Severity:
#     Error 

PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>

SELECT DISTINCT ?element ?definition ?error
WHERE {
  ?element cco:definition ?definition .
  ?element2 cco:definition ?definition .
  FILTER (?element != ?element2)
  FILTER (!isBlank(?element))
  BIND (concat("WARNING: The following ontology elements have the same cco:definition ", str(?element), " and ", str(?element2)) AS ?error)
}