# Title: 
#    No Duplicate Definitions
# Constraint Description: 
#    No two ontology elements may have the exact same definition.    
# Severity:
#     Error 

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?element ?definition ?error
WHERE {
  ?element skos:definition ?definition .
  ?element2 skos:definition ?definition .
  FILTER (?element != ?element2)
  FILTER (!isBlank(?element))
  BIND (concat("WARNING: The following ontology elements have the same cco:definition ", str(?element), " and ", str(?element2)) AS ?error)
}
