# Title: 
#    Definition Required
# Constraint Description: 
#    Any class or object property must have a non-empty defintiion with an English language tag.  
# Severity:
#     Warning

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>

SELECT DISTINCT ?resource ?label
WHERE {
VALUES ?type {owl:Class owl:ObjectProperty}
    ?resource a ?type .
    OPTIONAL {
        ?resource cco:definition ?englishDefinition .
        FILTER (langMatches(lang(?englishDefinition), "en"))
        }
    FILTER(!bound(?englishDefinition))
    FILTER(!isBlank(?resource))
}
ORDER BY ?resource
