# Title: 
#     Ontology Title Required
# Constraint Description: 
#     Any owl:Ontology must have a dcterms:title annotation property.
# Severity:
#     Warning

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?resource
WHERE
{
    ?resource a owl:Ontology .
    FILTER (!ISBLANK (?resource)) .
    FILTER NOT EXISTS {?resource rdfs:label ?title}
}