# Title: 
#     No Orphaned Subclasses
# Constraint Description: 
#     All CCO classes must have a superclass.
# Severity:
#     Error
# Author:
#	 github.com/swartik

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?cls
WHERE {
  ?cls a owl:Class
  FILTER isIRI(?cls)
  FILTER NOT EXISTS { ?cls rdfs:subClassOf ?supercls }
  FILTER (?cls != <http://purl.obolibrary.org/obo/BFO_0000001>)
}
