# Title:  
#    No Multiple Inverse Object Properties
# Constraint Description:  
#    Object properties should not have more than one inverse property.
# Severity:  
#    Error

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?property ?inverse1 ?inverse2 ?error
WHERE
{
  {
    { ?property owl:inverseOf ?inverse1 }
    UNION
    { ?inverse1 owl:inverseOf ?property }
  }
  {
    { ?property owl:inverseOf ?inverse2 }
    UNION
    { ?inverse2 owl:inverseOf ?property }
  }
  FILTER (?inverse1 != ?inverse2)
  FILTER (STR(?inverse1) < STR(?inverse2))
  BIND (concat("ERROR: Object property ", str(?property), " has more than one inverse.") AS ?error)
}
ORDER BY ?property