# Title:  
#    No Reflexive SubclassOf 
# Constraint Description:  
#    No class should be asserted as a subclass of itself.
# Severity:  
#    Error

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

SELECT ?class ?warningMessage
WHERE {
  ?class a owl:Class .

  FILTER (!ISBLANK(?class)) .

  ?class rdfs:subClassOf ?class .

  OPTIONAL {
    ?class rdfs:label ?label .
  }

  BIND(
    CONCAT(
      "Warning: Class ",
      COALESCE(STR(?label), STR(?class)),
      " is explicitly asserted as a subclass of itself"
    )
    AS ?warningMessage
  )
}