name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

permissions:
  contents: read

env:
  cache-path: build/lib
  artifacts-path: build/artifacts
  release-build-content-type: application/ttl
  cache-key: build-cache-dependencies

jobs:
  ontology_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached dependencies
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-${{ env.cache-key }}

      - name: List directory contents
        run: ls -la

      - name: Build and test ontology release
        run: make all

      - name: Capture release information
        id: build_release
        run: |
          echo "RELEASE_FILE_PATH=$(make output-release-filepath)" >> $GITHUB_OUTPUT
          echo "RELEASE_NAME=$(make output-release-name)" >> $GITHUB_OUTPUT

      - name: Display build information
        run: |
          echo "Release name: ${{ steps.build_release.outputs.RELEASE_NAME }}"
          echo "Release file: ${{ steps.build_release.outputs.RELEASE_FILE_PATH }}"

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ontology_release_results
          path: ${{ env.artifacts-path }}
          if-no-files-found: warn

      - name: Save dependencies to cache
        id: save-cache
        uses: actions/cache/save@v4
        if: always() && steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-${{ env.cache-key }}

      - name: Get basename of the release file
        id: get_basename
        run: |
          echo "BASENAME=$(basename '${{ steps.build_release.outputs.RELEASE_FILE_PATH }}')" >> $GITHUB_ENV

      - name: Display release artifact basename
        run: |
          echo "Release artifact basename: $BASENAME"